### ISSUE TITLE
top row mirrored from bottom row

### ISSUE THREAD

**Issue by Ichunjo** [WolframRhodium/VapourSynth-BilateralGPU#3]
Hello,
I noticed the top row of this sample are like mirrored from the bottom row. You can see a darker blurred row at the top of bilateralgpu and bilateralgpu_rtc while tcanny doesn't have this issue.

```py
clip.tcanny.TCanny(1, 1, mode=-1).set_output(0)
clip.bilateralgpu.Bilateral(1, 1.0).set_output(1)
clip.bilateralgpu_rtc.Bilateral(1, 1.0).set_output(2)
```

https://slow.pics/c/SWQNdew5

**Comment by Ichunjo** [comment]
Zoomed-in
![image](https://user-images.githubusercontent.com/23151870/147278836-cf91c8e5-5253-43db-b9d3-1c83fd54d845.png)
![image](https://user-images.githubusercontent.com/23151870/147278853-a90e8a29-e097-4242-b950-941bc10b3b8e.png)

**Comment by Ichunjo** [comment]
Nevermind https://github.com/WolframRhodium/VapourSynth-BilateralGPU/commit/a862d3e9a2915254fcb3ac6d2c18942dac92c67b fixed it.

**Comment by WolframRhodium** [comment]
Thanks for verification.
